import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const gilroy = localFont({
  variable: "--font-gilroy",
  src: [
    {
      path: "./fonts/Gilroy-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Medium.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

const gilmer = localFont({
  variable: "--font-gilmer",
  src: [
    {
      path: "./fonts/Gilmer-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gilmer-Medium.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Gilmer-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gilroy.variable} ${gilmer.variable} antialiased`}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
